# Copyright 2017. All Rights Reserved.
# Author: huiding7@gmail.com (Hui Ding)

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "base",
    srcs = [
        "base.h",
    ],
)
